Traceback (most recent call last):
  File "/home/obm/Prog/miniconda3/envs/qml/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/obm/Prog/miniconda3/envs/qml/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/obm/Prog/miniconda3/envs/qml/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/obm/Prog/miniconda3/envs/qml/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/obm/Prog/miniconda3/envs/qml/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/obm/Prog/miniconda3/envs/qml/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/obm/Prog/miniconda3/envs/qml/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/obm/Prog/miniconda3/envs/qml/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
geo_file = "files/h2.xyz"

symbols, coordinates = qml.qchem.read_structure(geo_file)
hamiltonian, qubits = qml.qchem.molecular_hamiltonian(symbols, coordinates)

print("Number of qubits = ", qubits)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Input [0;32mIn [8][0m, in [0;36m<cell line: 3>[0;34m()[0m
[1;32m      1[0m geo_file [38;5;241m=[39m [38;5;124m"[39m[38;5;124mfiles/h2.xyz[39m[38;5;124m"[39m
[0;32m----> 3[0m symbols, coordinates [38;5;241m=[39m [43mqml[49m[38;5;241;43m.[39;49m[43mqchem[49m[38;5;241;43m.[39;49m[43mread_structure[49m[43m([49m[43mgeo_file[49m[43m)[49m
[1;32m      4[0m hamiltonian, qubits [38;5;241m=[39m qml[38;5;241m.[39mqchem[38;5;241m.[39mmolecular_hamiltonian(symbols, coordinates)
[1;32m      6[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mNumber of qubits = [39m[38;5;124m"[39m, qubits)

File [0;32m~/Prog/miniconda3/envs/qml/lib/python3.8/site-packages/pennylane/qchem/structure.py:56[0m, in [0;36mread_structure[0;34m(filepath, outpath)[0m
[1;32m     53[0m file_in [38;5;241m=[39m filepath[38;5;241m.[39mstrip()
[1;32m     54[0m file_out [38;5;241m=[39m os[38;5;241m.[39mpath[38;5;241m.[39mjoin(outpath, [38;5;124m"[39m[38;5;124mstructure.xyz[39m[38;5;124m"[39m)
[0;32m---> 56[0m [43mcopyfile[49m[43m([49m[43mfile_in[49m[43m,[49m[43m [49m[43mfile_out[49m[43m)[49m
[1;32m     58[0m symbols [38;5;241m=[39m []
[1;32m     59[0m coordinates [38;5;241m=[39m []

File [0;32m~/Prog/miniconda3/envs/qml/lib/python3.8/shutil.py:264[0m, in [0;36mcopyfile[0;34m(src, dst, follow_symlinks)[0m
[1;32m    262[0m     os[38;5;241m.[39msymlink(os[38;5;241m.[39mreadlink(src), dst)
[1;32m    263[0m [38;5;28;01melse[39;00m:
[0;32m--> 264[0m     [38;5;28;01mwith[39;00m [38;5;28;43mopen[39;49m[43m([49m[43msrc[49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mrb[39;49m[38;5;124;43m'[39;49m[43m)[49m [38;5;28;01mas[39;00m fsrc, [38;5;28mopen[39m(dst, [38;5;124m'[39m[38;5;124mwb[39m[38;5;124m'[39m) [38;5;28;01mas[39;00m fdst:
[1;32m    265[0m         [38;5;66;03m# macOS[39;00m
[1;32m    266[0m         [38;5;28;01mif[39;00m _HAS_FCOPYFILE:
[1;32m    267[0m             [38;5;28;01mtry[39;00m:

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'files/h2.xyz'
FileNotFoundError: [Errno 2] No such file or directory: 'files/h2.xyz'

